### ISSUE TITLE
Support for show and list functions

### ISSUE THREAD

**Issue by weskerfoot** [mordae/racket-couchdb#1]
Would be nice to have support for the show and list function API that CouchDB has.

**Comment by mordae** [comment]
It should not be a problem, but I fail to see the point, since show/list is intended for couchapps and not for a standalone application that usually does the rendering through it's own templates. Can you describe your use-case please?

**Comment by weskerfoot** [comment]
It would simply be a way to get database side processing done instead of doing it on the application side. Though you're right in saying that it's not really that important for a standalone application.

**Comment by mordae** [comment]
OK, I'll look into that.

**Comment by mordae** [comment]
Discarding.
